//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.239
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using VotGES.Web.Services;
    
    
    /// <summary>
    /// Контекст полнофункционального интернет-приложения (RIA).
    /// </summary>
    /// <remarks>
    /// Данный контекст расширяет базовый и делает доступными службы и типы приложений,
    /// которые могут быть использованы в коде и xaml.
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Инициализирует новый экземпляр класса WebContext.
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает контекст, зарегистрированный как объект времени существования в данном приложении.
        /// </summary>
        /// Исключение <exception cref="InvalidOperationException"> вызывается в том случае, если отсутствует текущее приложение,
        /// не добавлено ни одного контекста либо было добавлено более одного контекста.
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
        
        /// <summary>
        /// Возвращает пользователя, прошедшего проверку подлинности.
        /// </summary>
        public new User User
        {
            get
            {
                return ((User)(base.User));
            }
        }
    }
}
namespace VotGES.Chart
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// Класс "ChartAnswer".
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/VotGES.Chart")]
    public sealed partial class ChartAnswer : ComplexObject
    {
        
        private ChartData _data;
        
        private ChartProperties _properties;
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();
        partial void OnDataChanging(ChartData value);
        partial void OnDataChanged();
        partial void OnPropertiesChanging(ChartProperties value);
        partial void OnPropertiesChanged();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="ChartAnswer"/>.
        /// </summary>
        public ChartAnswer()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Data".
        /// </summary>
        [DataMember()]
        [Display(AutoGenerateField=false)]
        public ChartData Data
        {
            get
            {
                return this._data;
            }
            set
            {
                if ((this._data != value))
                {
                    this.OnDataChanging(value);
                    this.RaiseDataMemberChanging("Data");
                    this.ValidateProperty("Data", value);
                    this._data = value;
                    this.RaiseDataMemberChanged("Data");
                    this.OnDataChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Properties".
        /// </summary>
        [DataMember()]
        [Display(AutoGenerateField=false)]
        public ChartProperties Properties
        {
            get
            {
                return this._properties;
            }
            set
            {
                if ((this._properties != value))
                {
                    this.OnPropertiesChanging(value);
                    this.RaiseDataMemberChanging("Properties");
                    this.ValidateProperty("Properties", value);
                    this._properties = value;
                    this.RaiseDataMemberChanged("Properties");
                    this.OnPropertiesChanged();
                }
            }
        }
    }
    
    /// <summary>
    /// Класс "ChartAxisProperties".
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/VotGES.Chart")]
    public sealed partial class ChartAxisProperties : ComplexObject
    {
        
        private bool _auto;
        
        private int _index;
        
        private double _interval;
        
        private double _max;
        
        private double _min;
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();
        partial void OnAutoChanging(bool value);
        partial void OnAutoChanged();
        partial void OnIndexChanging(int value);
        partial void OnIndexChanged();
        partial void OnIntervalChanging(double value);
        partial void OnIntervalChanged();
        partial void OnMaxChanging(double value);
        partial void OnMaxChanged();
        partial void OnMinChanging(double value);
        partial void OnMinChanged();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="ChartAxisProperties"/>.
        /// </summary>
        public ChartAxisProperties()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Auto".
        /// </summary>
        [DataMember()]
        public bool Auto
        {
            get
            {
                return this._auto;
            }
            set
            {
                if ((this._auto != value))
                {
                    this.OnAutoChanging(value);
                    this.RaiseDataMemberChanging("Auto");
                    this.ValidateProperty("Auto", value);
                    this._auto = value;
                    this.RaiseDataMemberChanged("Auto");
                    this.OnAutoChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Index".
        /// </summary>
        [DataMember()]
        public int Index
        {
            get
            {
                return this._index;
            }
            set
            {
                if ((this._index != value))
                {
                    this.OnIndexChanging(value);
                    this.RaiseDataMemberChanging("Index");
                    this.ValidateProperty("Index", value);
                    this._index = value;
                    this.RaiseDataMemberChanged("Index");
                    this.OnIndexChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Interval".
        /// </summary>
        [DataMember()]
        public double Interval
        {
            get
            {
                return this._interval;
            }
            set
            {
                if ((this._interval != value))
                {
                    this.OnIntervalChanging(value);
                    this.RaiseDataMemberChanging("Interval");
                    this.ValidateProperty("Interval", value);
                    this._interval = value;
                    this.RaiseDataMemberChanged("Interval");
                    this.OnIntervalChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Max".
        /// </summary>
        [DataMember()]
        public double Max
        {
            get
            {
                return this._max;
            }
            set
            {
                if ((this._max != value))
                {
                    this.OnMaxChanging(value);
                    this.RaiseDataMemberChanging("Max");
                    this.ValidateProperty("Max", value);
                    this._max = value;
                    this.RaiseDataMemberChanged("Max");
                    this.OnMaxChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Min".
        /// </summary>
        [DataMember()]
        public double Min
        {
            get
            {
                return this._min;
            }
            set
            {
                if ((this._min != value))
                {
                    this.OnMinChanging(value);
                    this.RaiseDataMemberChanging("Min");
                    this.ValidateProperty("Min", value);
                    this._min = value;
                    this.RaiseDataMemberChanged("Min");
                    this.OnMinChanged();
                }
            }
        }
    }
    
    /// <summary>
    /// Класс "ChartData".
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/VotGES.Chart")]
    [XmlRoot(ElementName="chart")]
    public sealed partial class ChartData : ComplexObject
    {
        
        private List<ChartDataSerie> _series;
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();
        partial void OnSeriesChanging(List<ChartDataSerie> value);
        partial void OnSeriesChanged();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="ChartData"/>.
        /// </summary>
        public ChartData()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Series".
        /// </summary>
        [DataMember()]
        [Display(AutoGenerateField=false)]
        public List<ChartDataSerie> Series
        {
            get
            {
                return this._series;
            }
            set
            {
                if ((this._series != value))
                {
                    this.OnSeriesChanging(value);
                    this.RaiseDataMemberChanging("Series");
                    this.ValidateProperty("Series", value);
                    this._series = value;
                    this.RaiseDataMemberChanged("Series");
                    this.OnSeriesChanged();
                }
            }
        }
    }
    
    /// <summary>
    /// Класс "ChartDataPoint".
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/VotGES.Chart")]
    public sealed partial class ChartDataPoint : ComplexObject
    {
        
        private string _xVal;
        
        private double _yVal;
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();
        partial void OnXValChanging(string value);
        partial void OnXValChanged();
        partial void OnYValChanging(double value);
        partial void OnYValChanged();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="ChartDataPoint"/>.
        /// </summary>
        public ChartDataPoint()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "XVal".
        /// </summary>
        [DataMember()]
        public string XVal
        {
            get
            {
                return this._xVal;
            }
            set
            {
                if ((this._xVal != value))
                {
                    this.OnXValChanging(value);
                    this.RaiseDataMemberChanging("XVal");
                    this.ValidateProperty("XVal", value);
                    this._xVal = value;
                    this.RaiseDataMemberChanged("XVal");
                    this.OnXValChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "YVal".
        /// </summary>
        [DataMember()]
        public double YVal
        {
            get
            {
                return this._yVal;
            }
            set
            {
                if ((this._yVal != value))
                {
                    this.OnYValChanging(value);
                    this.RaiseDataMemberChanging("YVal");
                    this.ValidateProperty("YVal", value);
                    this._yVal = value;
                    this.RaiseDataMemberChanged("YVal");
                    this.OnYValChanged();
                }
            }
        }
    }
    
    /// <summary>
    /// Класс "ChartDataSerie".
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/VotGES.Chart")]
    public sealed partial class ChartDataSerie : ComplexObject
    {
        
        private string _name;
        
        private List<ChartDataPoint> _points;
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnPointsChanging(List<ChartDataPoint> value);
        partial void OnPointsChanged();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="ChartDataSerie"/>.
        /// </summary>
        public ChartDataSerie()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Name".
        /// </summary>
        [DataMember()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((this._name != value))
                {
                    this.OnNameChanging(value);
                    this.RaiseDataMemberChanging("Name");
                    this.ValidateProperty("Name", value);
                    this._name = value;
                    this.RaiseDataMemberChanged("Name");
                    this.OnNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Points".
        /// </summary>
        [DataMember()]
        [Display(AutoGenerateField=false)]
        public List<ChartDataPoint> Points
        {
            get
            {
                return this._points;
            }
            set
            {
                if ((this._points != value))
                {
                    this.OnPointsChanging(value);
                    this.RaiseDataMemberChanging("Points");
                    this.ValidateProperty("Points", value);
                    this._points = value;
                    this.RaiseDataMemberChanged("Points");
                    this.OnPointsChanged();
                }
            }
        }
    }
    
    /// <summary>
    /// Класс "ChartProperties".
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/VotGES.Chart")]
    public sealed partial class ChartProperties : ComplexObject
    {
        
        private List<ChartAxisProperties> _axes;
        
        private List<ChartSerieProperties> _series;
        
        private XAxisTypeEnum _xAxisType;
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();
        partial void OnAxesChanging(List<ChartAxisProperties> value);
        partial void OnAxesChanged();
        partial void OnSeriesChanging(List<ChartSerieProperties> value);
        partial void OnSeriesChanged();
        partial void OnXAxisTypeChanging(XAxisTypeEnum value);
        partial void OnXAxisTypeChanged();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="ChartProperties"/>.
        /// </summary>
        public ChartProperties()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Axes".
        /// </summary>
        [DataMember()]
        [Display(AutoGenerateField=false)]
        public List<ChartAxisProperties> Axes
        {
            get
            {
                return this._axes;
            }
            set
            {
                if ((this._axes != value))
                {
                    this.OnAxesChanging(value);
                    this.RaiseDataMemberChanging("Axes");
                    this.ValidateProperty("Axes", value);
                    this._axes = value;
                    this.RaiseDataMemberChanged("Axes");
                    this.OnAxesChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Series".
        /// </summary>
        [DataMember()]
        [Display(AutoGenerateField=false)]
        public List<ChartSerieProperties> Series
        {
            get
            {
                return this._series;
            }
            set
            {
                if ((this._series != value))
                {
                    this.OnSeriesChanging(value);
                    this.RaiseDataMemberChanging("Series");
                    this.ValidateProperty("Series", value);
                    this._series = value;
                    this.RaiseDataMemberChanged("Series");
                    this.OnSeriesChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "XAxisType".
        /// </summary>
        [DataMember()]
        public XAxisTypeEnum XAxisType
        {
            get
            {
                return this._xAxisType;
            }
            set
            {
                if ((this._xAxisType != value))
                {
                    this.OnXAxisTypeChanging(value);
                    this.RaiseDataMemberChanging("XAxisType");
                    this.ValidateProperty("XAxisType", value);
                    this._xAxisType = value;
                    this.RaiseDataMemberChanged("XAxisType");
                    this.OnXAxisTypeChanged();
                }
            }
        }
    }
    
    /// <summary>
    /// Класс "ChartSerieProperties".
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/VotGES.Chart")]
    public sealed partial class ChartSerieProperties : ComplexObject
    {
        
        private string _color;
        
        private bool _enabled;
        
        private int _lineWidth;
        
        private bool _marker;
        
        private ChartSerieType _serieType;
        
        private string _tagName;
        
        private string _title;
        
        private int _yAxisIndex;
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();
        partial void OnColorChanging(string value);
        partial void OnColorChanged();
        partial void OnEnabledChanging(bool value);
        partial void OnEnabledChanged();
        partial void OnLineWidthChanging(int value);
        partial void OnLineWidthChanged();
        partial void OnMarkerChanging(bool value);
        partial void OnMarkerChanged();
        partial void OnSerieTypeChanging(ChartSerieType value);
        partial void OnSerieTypeChanged();
        partial void OnTagNameChanging(string value);
        partial void OnTagNameChanged();
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        partial void OnYAxisIndexChanging(int value);
        partial void OnYAxisIndexChanged();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="ChartSerieProperties"/>.
        /// </summary>
        public ChartSerieProperties()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Color".
        /// </summary>
        [DataMember()]
        public string Color
        {
            get
            {
                return this._color;
            }
            set
            {
                if ((this._color != value))
                {
                    this.OnColorChanging(value);
                    this.RaiseDataMemberChanging("Color");
                    this.ValidateProperty("Color", value);
                    this._color = value;
                    this.RaiseDataMemberChanged("Color");
                    this.OnColorChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Enabled".
        /// </summary>
        [DataMember()]
        public bool Enabled
        {
            get
            {
                return this._enabled;
            }
            set
            {
                if ((this._enabled != value))
                {
                    this.OnEnabledChanging(value);
                    this.RaiseDataMemberChanging("Enabled");
                    this.ValidateProperty("Enabled", value);
                    this._enabled = value;
                    this.RaiseDataMemberChanged("Enabled");
                    this.OnEnabledChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "LineWidth".
        /// </summary>
        [DataMember()]
        public int LineWidth
        {
            get
            {
                return this._lineWidth;
            }
            set
            {
                if ((this._lineWidth != value))
                {
                    this.OnLineWidthChanging(value);
                    this.RaiseDataMemberChanging("LineWidth");
                    this.ValidateProperty("LineWidth", value);
                    this._lineWidth = value;
                    this.RaiseDataMemberChanged("LineWidth");
                    this.OnLineWidthChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Marker".
        /// </summary>
        [DataMember()]
        public bool Marker
        {
            get
            {
                return this._marker;
            }
            set
            {
                if ((this._marker != value))
                {
                    this.OnMarkerChanging(value);
                    this.RaiseDataMemberChanging("Marker");
                    this.ValidateProperty("Marker", value);
                    this._marker = value;
                    this.RaiseDataMemberChanged("Marker");
                    this.OnMarkerChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "SerieType".
        /// </summary>
        [DataMember()]
        public ChartSerieType SerieType
        {
            get
            {
                return this._serieType;
            }
            set
            {
                if ((this._serieType != value))
                {
                    this.OnSerieTypeChanging(value);
                    this.RaiseDataMemberChanging("SerieType");
                    this.ValidateProperty("SerieType", value);
                    this._serieType = value;
                    this.RaiseDataMemberChanged("SerieType");
                    this.OnSerieTypeChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "TagName".
        /// </summary>
        [DataMember()]
        public string TagName
        {
            get
            {
                return this._tagName;
            }
            set
            {
                if ((this._tagName != value))
                {
                    this.OnTagNameChanging(value);
                    this.RaiseDataMemberChanging("TagName");
                    this.ValidateProperty("TagName", value);
                    this._tagName = value;
                    this.RaiseDataMemberChanged("TagName");
                    this.OnTagNameChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Title".
        /// </summary>
        [DataMember()]
        public string Title
        {
            get
            {
                return this._title;
            }
            set
            {
                if ((this._title != value))
                {
                    this.OnTitleChanging(value);
                    this.RaiseDataMemberChanging("Title");
                    this.ValidateProperty("Title", value);
                    this._title = value;
                    this.RaiseDataMemberChanged("Title");
                    this.OnTitleChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "YAxisIndex".
        /// </summary>
        [DataMember()]
        public int YAxisIndex
        {
            get
            {
                return this._yAxisIndex;
            }
            set
            {
                if ((this._yAxisIndex != value))
                {
                    this.OnYAxisIndexChanging(value);
                    this.RaiseDataMemberChanging("YAxisIndex");
                    this.ValidateProperty("YAxisIndex", value);
                    this._yAxisIndex = value;
                    this.RaiseDataMemberChanged("YAxisIndex");
                    this.OnYAxisIndexChanged();
                }
            }
        }
    }
    
    public enum ChartSerieType
    {
        
        line = 0,
        
        bar = 1,
        
        pie = 2,
        
        column = 3,
        
        stepLine = 4,
    }
    
    public enum XAxisTypeEnum
    {
        
        auto = 0,
        
        datetime = 1,
    }
}
namespace VotGES.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// Класс "GAParams".
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/VotGES.Web.Models")]
    public sealed partial class GAParams : ComplexObject
    {
        
        private bool _avail;
        
        private int _gaNumber;
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();
        partial void OnAvailChanging(bool value);
        partial void OnAvailChanged();
        partial void OnGaNumberChanging(int value);
        partial void OnGaNumberChanged();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="GAParams"/>.
        /// </summary>
        public GAParams()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Avail".
        /// </summary>
        [DataMember()]
        public bool Avail
        {
            get
            {
                return this._avail;
            }
            set
            {
                if ((this._avail != value))
                {
                    this.OnAvailChanging(value);
                    this.RaiseDataMemberChanging("Avail");
                    this.ValidateProperty("Avail", value);
                    this._avail = value;
                    this.RaiseDataMemberChanged("Avail");
                    this.OnAvailChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "GaNumber".
        /// </summary>
        [DataMember()]
        public int GaNumber
        {
            get
            {
                return this._gaNumber;
            }
            set
            {
                if ((this._gaNumber != value))
                {
                    this.OnGaNumberChanging(value);
                    this.RaiseDataMemberChanging("GaNumber");
                    this.ValidateProperty("GaNumber", value);
                    this._gaNumber = value;
                    this.RaiseDataMemberChanged("GaNumber");
                    this.OnGaNumberChanged();
                }
            }
        }
    }
    
    /// <summary>
    /// Класс "RUSAData".
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/VotGES.Web.Models")]
    public sealed partial class RUSAData : ComplexObject
    {
        
        private List<RUSAResult> _diffResult;
        
        private List<RUSAResult> _eqResult;
        
        private List<GAParams> _gaAvail;
        
        private Guid _id;
        
        private double _napor;
        
        private double _power;
        
        private List<RUSAResult> _result;
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();
        partial void OnDiffResultChanging(List<RUSAResult> value);
        partial void OnDiffResultChanged();
        partial void OnEqResultChanging(List<RUSAResult> value);
        partial void OnEqResultChanged();
        partial void OnGaAvailChanging(List<GAParams> value);
        partial void OnGaAvailChanged();
        partial void OnIdChanging(Guid value);
        partial void OnIdChanged();
        partial void OnNaporChanging(double value);
        partial void OnNaporChanged();
        partial void OnPowerChanging(double value);
        partial void OnPowerChanged();
        partial void OnResultChanging(List<RUSAResult> value);
        partial void OnResultChanged();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="RUSAData"/>.
        /// </summary>
        public RUSAData()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "DiffResult".
        /// </summary>
        [DataMember()]
        [Display(AutoGenerateField=false)]
        public List<RUSAResult> DiffResult
        {
            get
            {
                return this._diffResult;
            }
            set
            {
                if ((this._diffResult != value))
                {
                    this.OnDiffResultChanging(value);
                    this.RaiseDataMemberChanging("DiffResult");
                    this.ValidateProperty("DiffResult", value);
                    this._diffResult = value;
                    this.RaiseDataMemberChanged("DiffResult");
                    this.OnDiffResultChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "EqResult".
        /// </summary>
        [DataMember()]
        [Display(AutoGenerateField=false)]
        public List<RUSAResult> EqResult
        {
            get
            {
                return this._eqResult;
            }
            set
            {
                if ((this._eqResult != value))
                {
                    this.OnEqResultChanging(value);
                    this.RaiseDataMemberChanging("EqResult");
                    this.ValidateProperty("EqResult", value);
                    this._eqResult = value;
                    this.RaiseDataMemberChanged("EqResult");
                    this.OnEqResultChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "GaAvail".
        /// </summary>
        [DataMember()]
        [Display(AutoGenerateField=false)]
        public List<GAParams> GaAvail
        {
            get
            {
                return this._gaAvail;
            }
            set
            {
                if ((this._gaAvail != value))
                {
                    this.OnGaAvailChanging(value);
                    this.RaiseDataMemberChanging("GaAvail");
                    this.ValidateProperty("GaAvail", value);
                    this._gaAvail = value;
                    this.RaiseDataMemberChanged("GaAvail");
                    this.OnGaAvailChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Id".
        /// </summary>
        [DataMember()]
        public Guid Id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnIdChanging(value);
                    this.RaiseDataMemberChanging("Id");
                    this.ValidateProperty("Id", value);
                    this._id = value;
                    this.RaiseDataMemberChanged("Id");
                    this.OnIdChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Napor".
        /// </summary>
        [DataMember()]
        public double Napor
        {
            get
            {
                return this._napor;
            }
            set
            {
                if ((this._napor != value))
                {
                    this.OnNaporChanging(value);
                    this.RaiseDataMemberChanging("Napor");
                    this.ValidateProperty("Napor", value);
                    this._napor = value;
                    this.RaiseDataMemberChanged("Napor");
                    this.OnNaporChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Power".
        /// </summary>
        [DataMember()]
        public double Power
        {
            get
            {
                return this._power;
            }
            set
            {
                if ((this._power != value))
                {
                    this.OnPowerChanging(value);
                    this.RaiseDataMemberChanging("Power");
                    this.ValidateProperty("Power", value);
                    this._power = value;
                    this.RaiseDataMemberChanged("Power");
                    this.OnPowerChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Result".
        /// </summary>
        [DataMember()]
        [Display(AutoGenerateField=false)]
        public List<RUSAResult> Result
        {
            get
            {
                return this._result;
            }
            set
            {
                if ((this._result != value))
                {
                    this.OnResultChanging(value);
                    this.RaiseDataMemberChanging("Result");
                    this.ValidateProperty("Result", value);
                    this._result = value;
                    this.RaiseDataMemberChanged("Result");
                    this.OnResultChanged();
                }
            }
        }
    }
    
    /// <summary>
    /// Класс "RUSAResult".
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/VotGES.Web.Models")]
    public sealed partial class RUSAResult : ComplexObject
    {
        
        private double _kpd;
        
        private double _rashod;
        
        private Dictionary<int, double> _sostav;
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();
        partial void OnKPDChanging(double value);
        partial void OnKPDChanged();
        partial void OnRashodChanging(double value);
        partial void OnRashodChanged();
        partial void OnSostavChanging(Dictionary<int, double> value);
        partial void OnSostavChanged();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="RUSAResult"/>.
        /// </summary>
        public RUSAResult()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "KPD".
        /// </summary>
        [DataMember()]
        public double KPD
        {
            get
            {
                return this._kpd;
            }
            set
            {
                if ((this._kpd != value))
                {
                    this.OnKPDChanging(value);
                    this.RaiseDataMemberChanging("KPD");
                    this.ValidateProperty("KPD", value);
                    this._kpd = value;
                    this.RaiseDataMemberChanged("KPD");
                    this.OnKPDChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Rashod".
        /// </summary>
        [DataMember()]
        public double Rashod
        {
            get
            {
                return this._rashod;
            }
            set
            {
                if ((this._rashod != value))
                {
                    this.OnRashodChanging(value);
                    this.RaiseDataMemberChanging("Rashod");
                    this.ValidateProperty("Rashod", value);
                    this._rashod = value;
                    this.RaiseDataMemberChanged("Rashod");
                    this.OnRashodChanged();
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Sostav".
        /// </summary>
        [DataMember()]
        public Dictionary<int, double> Sostav
        {
            get
            {
                return this._sostav;
            }
            set
            {
                if ((this._sostav != value))
                {
                    this.OnSostavChanging(value);
                    this.RaiseDataMemberChanging("Sostav");
                    this.ValidateProperty("Sostav", value);
                    this._sostav = value;
                    this.RaiseDataMemberChanged("Sostav");
                    this.OnSostavChanged();
                }
            }
        }
    }
}
namespace VotGES.Web.Services
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.ServiceModel;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    using System.ServiceModel.Web;
    using VotGES.Chart;
    using VotGES.Web.Models;
    
    
    /// <summary>
    /// Контекст DomainContext, соответствующий службе "AuthenticationDomainService" DomainService.
    /// </summary>
    public sealed partial class AuthenticationDomainContext : global::System.ServiceModel.DomainServices.Client.ApplicationServices.AuthenticationDomainContextBase
    {
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="AuthenticationDomainContext"/>.
        /// </summary>
        public AuthenticationDomainContext() : 
                this(new WebDomainClient<IAuthenticationDomainServiceContract>(new Uri("VotGES-Web-Services-AuthenticationDomainService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Инициализирует новый экземпляр класса <see cref="AuthenticationDomainContext"/> с указанным URI службы.
        /// </summary>
        /// <param name="serviceUri">Идентификатор URI службы AuthenticationDomainService.</param>
        public AuthenticationDomainContext(Uri serviceUri) : 
                this(new WebDomainClient<IAuthenticationDomainServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Инициализирует новый экземпляр класса <see cref="AuthenticationDomainContext"/> с указанным параметром <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">Экземпляр DomainClient для использования в этом контексте DomainContext.</param>
        public AuthenticationDomainContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает набор экземпляров сущностей <see cref="User"/>, загруженных в данный экземпляр <see cref="AuthenticationDomainContext"/>.
        /// </summary>
        public EntitySet<User> Users
        {
            get
            {
                return base.EntityContainer.GetEntitySet<User>();
            }
        }
        
        /// <summary>
        /// Возвращает экземпляр EntityQuery, который может быть использован для загрузки экземпляров сущностей <see cref="User"/> с помощью запроса "GetUser".
        /// </summary>
        /// <returns>Значение EntityQuery, которое может быть загружено для извлечения экземпляров сущностей <see cref="User"/>.</returns>
        public EntityQuery<User> GetUserQuery()
        {
            this.ValidateMethod("GetUserQuery", null);
            return base.CreateQuery<User>("GetUser", null, false, false);
        }
        
        /// <summary>
        /// Возвращает экземпляр EntityQuery, который может быть использован для загрузки экземпляров сущностей <see cref="User"/> с помощью запроса "Login".
        /// </summary>
        /// <param name="userName">Значение параметра "userName" для запроса.</param>
        /// <param name="password">Значение параметра "password" для запроса.</param>
        /// <param name="isPersistent">Значение параметра "isPersistent" для запроса.</param>
        /// <param name="customData">Значение параметра "customData" для запроса.</param>
        /// <returns>Значение EntityQuery, которое может быть загружено для извлечения экземпляров сущностей <see cref="User"/>.</returns>
        public EntityQuery<User> LoginQuery(string userName, string password, bool isPersistent, string customData)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("userName", userName);
            parameters.Add("password", password);
            parameters.Add("isPersistent", isPersistent);
            parameters.Add("customData", customData);
            this.ValidateMethod("LoginQuery", parameters);
            return base.CreateQuery<User>("Login", parameters, true, false);
        }
        
        /// <summary>
        /// Возвращает экземпляр EntityQuery, который может быть использован для загрузки экземпляров сущностей <see cref="User"/> с помощью запроса "Logout".
        /// </summary>
        /// <returns>Значение EntityQuery, которое может быть загружено для извлечения экземпляров сущностей <see cref="User"/>.</returns>
        public EntityQuery<User> LogoutQuery()
        {
            this.ValidateMethod("LogoutQuery", null);
            return base.CreateQuery<User>("Logout", null, true, false);
        }
        
        /// <summary>
        /// Создает новый объект EntityContainer для наборов сущностей EntitySets данного контекста DomainContext.
        /// </summary>
        /// <returns>Новый экземпляр контейнера.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new AuthenticationDomainContextEntityContainer();
        }
        
        /// <summary>
        /// Контракт службы (Service) "AuthenticationDomainService" DomainService.
        /// </summary>
        [ServiceContract()]
        public interface IAuthenticationDomainServiceContract
        {
            
            /// <summary>
            /// Асинхронно вызывает операцию "GetUser".
            /// </summary>
            /// <param name="callback">Функция обратного вызова вызывается после завершения.</param>
            /// <param name="asyncState">Необязательный объект состояния.</param>
            /// <returns>Интерфейс IAsyncResult, который может быть использован для отслеживания запроса.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/AuthenticationDomainService/GetUserDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/AuthenticationDomainService/GetUser", ReplyAction="http://tempuri.org/AuthenticationDomainService/GetUserResponse")]
            [WebGet()]
            IAsyncResult BeginGetUser(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Завершает асинхронную операцию, начатую "BeginGetUser".
            /// </summary>
            /// <param name="result">Интерфейс IAsyncResult, возвращенный из "BeginGetUser".</param>
            /// <returns>Объект "QueryResult", возвращенный из операции "GetUser".</returns>
            QueryResult<User> EndGetUser(IAsyncResult result);
            
            /// <summary>
            /// Асинхронно вызывает операцию "Login".
            /// </summary>
            /// <param name="userName">Значение параметра "userName" для данного действия.</param>
            /// <param name="password">Значение параметра "password" для данного действия.</param>
            /// <param name="isPersistent">Значение параметра "isPersistent" для данного действия.</param>
            /// <param name="customData">Значение параметра "customData" для данного действия.</param>
            /// <param name="callback">Функция обратного вызова вызывается после завершения.</param>
            /// <param name="asyncState">Необязательный объект состояния.</param>
            /// <returns>Интерфейс IAsyncResult, который может быть использован для отслеживания запроса.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/AuthenticationDomainService/LoginDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/AuthenticationDomainService/Login", ReplyAction="http://tempuri.org/AuthenticationDomainService/LoginResponse")]
            IAsyncResult BeginLogin(string userName, string password, bool isPersistent, string customData, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Завершает асинхронную операцию, начатую "BeginLogin".
            /// </summary>
            /// <param name="result">Интерфейс IAsyncResult, возвращенный из "BeginLogin".</param>
            /// <returns>Объект "QueryResult", возвращенный из операции "Login".</returns>
            QueryResult<User> EndLogin(IAsyncResult result);
            
            /// <summary>
            /// Асинхронно вызывает операцию "Logout".
            /// </summary>
            /// <param name="callback">Функция обратного вызова вызывается после завершения.</param>
            /// <param name="asyncState">Необязательный объект состояния.</param>
            /// <returns>Интерфейс IAsyncResult, который может быть использован для отслеживания запроса.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/AuthenticationDomainService/LogoutDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/AuthenticationDomainService/Logout", ReplyAction="http://tempuri.org/AuthenticationDomainService/LogoutResponse")]
            IAsyncResult BeginLogout(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Завершает асинхронную операцию, начатую "BeginLogout".
            /// </summary>
            /// <param name="result">Интерфейс IAsyncResult, возвращенный из "BeginLogout".</param>
            /// <returns>Объект "QueryResult", возвращенный из операции "Logout".</returns>
            QueryResult<User> EndLogout(IAsyncResult result);
            
            /// <summary>
            /// Асинхронно вызывает операцию "SubmitChanges".
            /// </summary>
            /// <param name="changeSet">Набор изменений для отправки.</param>
            /// <param name="callback">Функция обратного вызова вызывается после завершения.</param>
            /// <param name="asyncState">Необязательный объект состояния.</param>
            /// <returns>Интерфейс IAsyncResult, который может быть использован для отслеживания запроса.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/AuthenticationDomainService/SubmitChangesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/AuthenticationDomainService/SubmitChanges", ReplyAction="http://tempuri.org/AuthenticationDomainService/SubmitChangesResponse")]
            IAsyncResult BeginSubmitChanges(IEnumerable<ChangeSetEntry> changeSet, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Завершает асинхронную операцию, начатую "BeginSubmitChanges".
            /// </summary>
            /// <param name="result">Интерфейс IAsyncResult, возвращенный из "BeginSubmitChanges".</param>
            /// <returns>Коллекция элементов набора изменений, возвращенного операцией SubmitChanges.</returns>
            IEnumerable<ChangeSetEntry> EndSubmitChanges(IAsyncResult result);
        }
        
        internal sealed class AuthenticationDomainContextEntityContainer : EntityContainer
        {
            
            public AuthenticationDomainContextEntityContainer()
            {
                this.CreateEntitySet<User>(EntitySetOperations.Edit);
            }
        }
    }
    
    /// <summary>
    /// Контекст DomainContext, соответствующий службе "ChartService" DomainService.
    /// </summary>
    public sealed partial class ChartContext : DomainContext
    {
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="ChartContext"/>.
        /// </summary>
        public ChartContext() : 
                this(new WebDomainClient<IChartServiceContract>(new Uri("VotGES-Web-Services-ChartService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Инициализирует новый экземпляр класса <see cref="ChartContext"/> с указанным URI службы.
        /// </summary>
        /// <param name="serviceUri">Идентификатор URI службы ChartService.</param>
        public ChartContext(Uri serviceUri) : 
                this(new WebDomainClient<IChartServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Инициализирует новый экземпляр класса <see cref="ChartContext"/> с указанным параметром <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">Экземпляр DomainClient для использования в этом контексте DomainContext.</param>
        public ChartContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Асинхронно вызывает метод "processChart" службы DomainService.
        /// </summary>
        /// <param name="callback">Функция обратного вызова вызывается после завершения операции.</param>
        /// <param name="userState">Параметр для передачи в функцию обратного вызова. Может быть равен <c>null</c>.</param>
        /// <returns>Экземпляр операции, который может быть использован для управления асинхронным запросом.</returns>
        public InvokeOperation<ChartAnswer> processChart(Action<InvokeOperation<ChartAnswer>> callback, object userState)
        {
            this.ValidateMethod("processChart", null);
            return ((InvokeOperation<ChartAnswer>)(this.InvokeOperation("processChart", typeof(ChartAnswer), null, true, callback, userState)));
        }
        
        /// <summary>
        /// Асинхронно вызывает метод "processChart" службы DomainService.
        /// </summary>
        /// <returns>Экземпляр операции, который может быть использован для управления асинхронным запросом.</returns>
        public InvokeOperation<ChartAnswer> processChart()
        {
            this.ValidateMethod("processChart", null);
            return ((InvokeOperation<ChartAnswer>)(this.InvokeOperation("processChart", typeof(ChartAnswer), null, true, null, null)));
        }
        
        /// <summary>
        /// Создает новый объект EntityContainer для наборов сущностей EntitySets данного контекста DomainContext.
        /// </summary>
        /// <returns>Новый экземпляр контейнера.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new ChartContextEntityContainer();
        }
        
        /// <summary>
        /// Контракт службы (Service) "ChartService" DomainService.
        /// </summary>
        [ServiceContract()]
        public interface IChartServiceContract
        {
            
            /// <summary>
            /// Асинхронно вызывает операцию "processChart".
            /// </summary>
            /// <param name="callback">Функция обратного вызова вызывается после завершения.</param>
            /// <param name="asyncState">Необязательный объект состояния.</param>
            /// <returns>Интерфейс IAsyncResult, который может быть использован для отслеживания запроса.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/ChartService/processChartDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/ChartService/processChart", ReplyAction="http://tempuri.org/ChartService/processChartResponse")]
            IAsyncResult BeginprocessChart(AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Завершает асинхронную операцию, начатую "BeginprocessChart".
            /// </summary>
            /// <param name="result">Интерфейс IAsyncResult, возвращенный из "BeginprocessChart".</param>
            /// <returns>Объект "ChartAnswer", возвращенный из операции "processChart".</returns>
            ChartAnswer EndprocessChart(IAsyncResult result);
        }
        
        internal sealed class ChartContextEntityContainer : EntityContainer
        {
            
            public ChartContextEntityContainer()
            {
            }
        }
    }
    
    /// <summary>
    /// Контекст DomainContext, соответствующий службе "LoggerService" DomainService.
    /// </summary>
    public sealed partial class LoggerContext : DomainContext
    {
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="LoggerContext"/>.
        /// </summary>
        public LoggerContext() : 
                this(new WebDomainClient<ILoggerServiceContract>(new Uri("VotGES-Web-Services-LoggerService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Инициализирует новый экземпляр класса <see cref="LoggerContext"/> с указанным URI службы.
        /// </summary>
        /// <param name="serviceUri">Идентификатор URI службы LoggerService.</param>
        public LoggerContext(Uri serviceUri) : 
                this(new WebDomainClient<ILoggerServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Инициализирует новый экземпляр класса <see cref="LoggerContext"/> с указанным параметром <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">Экземпляр DomainClient для использования в этом контексте DomainContext.</param>
        public LoggerContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Асинхронно вызывает метод "debug" службы DomainService.
        /// </summary>
        /// <param name="message">Значение параметра "message" для данного действия.</param>
        /// <param name="callback">Функция обратного вызова вызывается после завершения операции.</param>
        /// <param name="userState">Параметр для передачи в функцию обратного вызова. Может быть равен <c>null</c>.</param>
        /// <returns>Экземпляр операции, который может быть использован для управления асинхронным запросом.</returns>
        public InvokeOperation debug(string message, Action<InvokeOperation> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("message", message);
            this.ValidateMethod("debug", parameters);
            return this.InvokeOperation("debug", typeof(void), parameters, true, callback, userState);
        }
        
        /// <summary>
        /// Асинхронно вызывает метод "debug" службы DomainService.
        /// </summary>
        /// <param name="message">Значение параметра "message" для данного действия.</param>
        /// <returns>Экземпляр операции, который может быть использован для управления асинхронным запросом.</returns>
        public InvokeOperation debug(string message)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("message", message);
            this.ValidateMethod("debug", parameters);
            return this.InvokeOperation("debug", typeof(void), parameters, true, null, null);
        }
        
        /// <summary>
        /// Асинхронно вызывает метод "error" службы DomainService.
        /// </summary>
        /// <param name="message">Значение параметра "message" для данного действия.</param>
        /// <param name="callback">Функция обратного вызова вызывается после завершения операции.</param>
        /// <param name="userState">Параметр для передачи в функцию обратного вызова. Может быть равен <c>null</c>.</param>
        /// <returns>Экземпляр операции, который может быть использован для управления асинхронным запросом.</returns>
        public InvokeOperation error(string message, Action<InvokeOperation> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("message", message);
            this.ValidateMethod("error", parameters);
            return this.InvokeOperation("error", typeof(void), parameters, true, callback, userState);
        }
        
        /// <summary>
        /// Асинхронно вызывает метод "error" службы DomainService.
        /// </summary>
        /// <param name="message">Значение параметра "message" для данного действия.</param>
        /// <returns>Экземпляр операции, который может быть использован для управления асинхронным запросом.</returns>
        public InvokeOperation error(string message)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("message", message);
            this.ValidateMethod("error", parameters);
            return this.InvokeOperation("error", typeof(void), parameters, true, null, null);
        }
        
        /// <summary>
        /// Асинхронно вызывает метод "info" службы DomainService.
        /// </summary>
        /// <param name="message">Значение параметра "message" для данного действия.</param>
        /// <param name="callback">Функция обратного вызова вызывается после завершения операции.</param>
        /// <param name="userState">Параметр для передачи в функцию обратного вызова. Может быть равен <c>null</c>.</param>
        /// <returns>Экземпляр операции, который может быть использован для управления асинхронным запросом.</returns>
        public InvokeOperation info(string message, Action<InvokeOperation> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("message", message);
            this.ValidateMethod("info", parameters);
            return this.InvokeOperation("info", typeof(void), parameters, true, callback, userState);
        }
        
        /// <summary>
        /// Асинхронно вызывает метод "info" службы DomainService.
        /// </summary>
        /// <param name="message">Значение параметра "message" для данного действия.</param>
        /// <returns>Экземпляр операции, который может быть использован для управления асинхронным запросом.</returns>
        public InvokeOperation info(string message)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("message", message);
            this.ValidateMethod("info", parameters);
            return this.InvokeOperation("info", typeof(void), parameters, true, null, null);
        }
        
        /// <summary>
        /// Создает новый объект EntityContainer для наборов сущностей EntitySets данного контекста DomainContext.
        /// </summary>
        /// <returns>Новый экземпляр контейнера.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new LoggerContextEntityContainer();
        }
        
        /// <summary>
        /// Контракт службы (Service) "LoggerService" DomainService.
        /// </summary>
        [ServiceContract()]
        public interface ILoggerServiceContract
        {
            
            /// <summary>
            /// Асинхронно вызывает операцию "debug".
            /// </summary>
            /// <param name="message">Значение параметра "message" для данного действия.</param>
            /// <param name="callback">Функция обратного вызова вызывается после завершения.</param>
            /// <param name="asyncState">Необязательный объект состояния.</param>
            /// <returns>Интерфейс IAsyncResult, который может быть использован для отслеживания запроса.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/LoggerService/debugDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/LoggerService/debug", ReplyAction="http://tempuri.org/LoggerService/debugResponse")]
            IAsyncResult Begindebug(string message, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Завершает асинхронную операцию, начатую "Begindebug".
            /// </summary>
            /// <param name="result">Интерфейс IAsyncResult, возвращенный из "Begindebug".</param>
            void Enddebug(IAsyncResult result);
            
            /// <summary>
            /// Асинхронно вызывает операцию "error".
            /// </summary>
            /// <param name="message">Значение параметра "message" для данного действия.</param>
            /// <param name="callback">Функция обратного вызова вызывается после завершения.</param>
            /// <param name="asyncState">Необязательный объект состояния.</param>
            /// <returns>Интерфейс IAsyncResult, который может быть использован для отслеживания запроса.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/LoggerService/errorDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/LoggerService/error", ReplyAction="http://tempuri.org/LoggerService/errorResponse")]
            IAsyncResult Beginerror(string message, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Завершает асинхронную операцию, начатую "Beginerror".
            /// </summary>
            /// <param name="result">Интерфейс IAsyncResult, возвращенный из "Beginerror".</param>
            void Enderror(IAsyncResult result);
            
            /// <summary>
            /// Асинхронно вызывает операцию "info".
            /// </summary>
            /// <param name="message">Значение параметра "message" для данного действия.</param>
            /// <param name="callback">Функция обратного вызова вызывается после завершения.</param>
            /// <param name="asyncState">Необязательный объект состояния.</param>
            /// <returns>Интерфейс IAsyncResult, который может быть использован для отслеживания запроса.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/LoggerService/infoDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/LoggerService/info", ReplyAction="http://tempuri.org/LoggerService/infoResponse")]
            IAsyncResult Begininfo(string message, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Завершает асинхронную операцию, начатую "Begininfo".
            /// </summary>
            /// <param name="result">Интерфейс IAsyncResult, возвращенный из "Begininfo".</param>
            void Endinfo(IAsyncResult result);
        }
        
        internal sealed class LoggerContextEntityContainer : EntityContainer
        {
            
            public LoggerContextEntityContainer()
            {
            }
        }
    }
    
    /// <summary>
    /// Контекст DomainContext, соответствующий службе "RUSADomainService" DomainService.
    /// </summary>
    public sealed partial class RUSADomainContext : DomainContext
    {
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="RUSADomainContext"/>.
        /// </summary>
        public RUSADomainContext() : 
                this(new WebDomainClient<IRUSADomainServiceContract>(new Uri("VotGES-Web-Services-RUSADomainService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Инициализирует новый экземпляр класса <see cref="RUSADomainContext"/> с указанным URI службы.
        /// </summary>
        /// <param name="serviceUri">Идентификатор URI службы RUSADomainService.</param>
        public RUSADomainContext(Uri serviceUri) : 
                this(new WebDomainClient<IRUSADomainServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Инициализирует новый экземпляр класса <see cref="RUSADomainContext"/> с указанным параметром <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">Экземпляр DomainClient для использования в этом контексте DomainContext.</param>
        public RUSADomainContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Асинхронно вызывает метод "processRUSAData" службы DomainService.
        /// </summary>
        /// <param name="data">Значение параметра "data" для данного действия.</param>
        /// <param name="callback">Функция обратного вызова вызывается после завершения операции.</param>
        /// <param name="userState">Параметр для передачи в функцию обратного вызова. Может быть равен <c>null</c>.</param>
        /// <returns>Экземпляр операции, который может быть использован для управления асинхронным запросом.</returns>
        public InvokeOperation<RUSAData> processRUSAData(RUSAData data, Action<InvokeOperation<RUSAData>> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("data", data);
            this.ValidateMethod("processRUSAData", parameters);
            return ((InvokeOperation<RUSAData>)(this.InvokeOperation("processRUSAData", typeof(RUSAData), parameters, true, callback, userState)));
        }
        
        /// <summary>
        /// Асинхронно вызывает метод "processRUSAData" службы DomainService.
        /// </summary>
        /// <param name="data">Значение параметра "data" для данного действия.</param>
        /// <returns>Экземпляр операции, который может быть использован для управления асинхронным запросом.</returns>
        public InvokeOperation<RUSAData> processRUSAData(RUSAData data)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("data", data);
            this.ValidateMethod("processRUSAData", parameters);
            return ((InvokeOperation<RUSAData>)(this.InvokeOperation("processRUSAData", typeof(RUSAData), parameters, true, null, null)));
        }
        
        /// <summary>
        /// Создает новый объект EntityContainer для наборов сущностей EntitySets данного контекста DomainContext.
        /// </summary>
        /// <returns>Новый экземпляр контейнера.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new RUSADomainContextEntityContainer();
        }
        
        /// <summary>
        /// Контракт службы (Service) "RUSADomainService" DomainService.
        /// </summary>
        [ServiceContract()]
        public interface IRUSADomainServiceContract
        {
            
            /// <summary>
            /// Асинхронно вызывает операцию "processRUSAData".
            /// </summary>
            /// <param name="data">Значение параметра "data" для данного действия.</param>
            /// <param name="callback">Функция обратного вызова вызывается после завершения.</param>
            /// <param name="asyncState">Необязательный объект состояния.</param>
            /// <returns>Интерфейс IAsyncResult, который может быть использован для отслеживания запроса.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/RUSADomainService/processRUSADataDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/RUSADomainService/processRUSAData", ReplyAction="http://tempuri.org/RUSADomainService/processRUSADataResponse")]
            IAsyncResult BeginprocessRUSAData(RUSAData data, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Завершает асинхронную операцию, начатую "BeginprocessRUSAData".
            /// </summary>
            /// <param name="result">Интерфейс IAsyncResult, возвращенный из "BeginprocessRUSAData".</param>
            /// <returns>Объект "RUSAData", возвращенный из операции "processRUSAData".</returns>
            RUSAData EndprocessRUSAData(IAsyncResult result);
        }
        
        internal sealed class RUSADomainContextEntityContainer : EntityContainer
        {
            
            public RUSADomainContextEntityContainer()
            {
            }
        }
    }
    
    /// <summary>
    /// Класс сущности "User".
    /// </summary>
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/VotGES.Web.Services")]
    public sealed partial class User : Entity, global::System.Security.Principal.IIdentity, global::System.Security.Principal.IPrincipal
    {
        
        private string _name = string.Empty;
        
        private IEnumerable<string> _roles;
        
        #region Определение методов расширяемости

        /// <summary>
        /// Этот метод вызывается из конструктора по завершении инициализации и
        /// не может быть использован для последующей настройки объекта.
        /// </summary>
        partial void OnCreated();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnRolesChanging(IEnumerable<string> value);
        partial void OnRolesChanged();

        #endregion
        
        
        /// <summary>
        /// Инициализация нового экземпляра класса <see cref="User"/>.
        /// </summary>
        public User()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Name".
        /// </summary>
        [DataMember()]
        [Editable(false, AllowInitialValue=true)]
        [Key()]
        [RoundtripOriginal()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((this._name != value))
                {
                    this.OnNameChanging(value);
                    this.ValidateProperty("Name", value);
                    this._name = value;
                    this.RaisePropertyChanged("Name");
                    this.OnNameChanged();
                    this.RaisePropertyChanged("IsAuthenticated");
                }
            }
        }
        
        /// <summary>
        /// Возвращает или задает значение параметра "Roles".
        /// </summary>
        [DataMember()]
        [Editable(false)]
        public IEnumerable<string> Roles
        {
            get
            {
                return this._roles;
            }
            set
            {
                if ((this._roles != value))
                {
                    this.OnRolesChanging(value);
                    this.ValidateProperty("Roles", value);
                    this._roles = value;
                    this.RaisePropertyChanged("Roles");
                    this.OnRolesChanged();
                }
            }
        }
        
        string global::System.Security.Principal.IIdentity.AuthenticationType
        {
            get
            {
                return string.Empty;
            }
        }
        
        /// <summary>
        /// Возвращает значение, указывающее, проверена ли подлинность пользователя.
        /// </summary>
        /// <remarks>
        /// Это значение равно <c>true</c>, если <see cref="Name"/> не является пустым значением и не равно <c>null</c>.
        /// </remarks>
        public bool IsAuthenticated
        {
            get
            {
                return (true != string.IsNullOrEmpty(this.Name));
            }
        }
        
        string global::System.Security.Principal.IIdentity.Name
        {
            get
            {
                return this.Name;
            }
        }
        
        global::System.Security.Principal.IIdentity global::System.Security.Principal.IPrincipal.Identity
        {
            get
            {
                return this;
            }
        }
        
        /// <summary>
        /// Вычисляет значение ключевых полей, уникально идентифицирующее данный экземпляр сущности.
        /// </summary>
        /// <returns>Экземпляр объекта, уникально идентифицирующий данный экземпляр сущности.</returns>
        public override object GetIdentity()
        {
            return this._name;
        }
        
        /// <summary>
        /// Возвращает значение, указывающее, имеет ли участник данную роль.
        /// </summary>
        /// <remarks>
        /// Возвращает значение, указывающее, содержится ли указанная роль в списке ролей.
        /// Эта функция учитывает регистр символов.
        /// </remarks>
        /// <param name="role">Имя роли, членство в которой проверяется.</param>
        /// <returns>Возвращает значение, указывающее, имеет ли участник данную роль.</returns>
        public bool IsInRole(string role)
        {
            if ((this.Roles == null))
            {
                return false;
            }
            return global::System.Linq.Enumerable.Contains(this.Roles, role);
        }
    }
}
